version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: omniauth
    versions:
    - 2.0.1
    - 2.0.2
  - dependency-name: nokogiri
    versions:
    - 1.11.1
  - dependency-name: pry
    versions:
    - 0.13.1
